import React, { useState } from 'react';
import { 
  Sparkles, 
  Send, 
  CloudRain, 
  TrendingUp, 
  AlertTriangle, 
  ChefHat, 
  CheckCircle2, 
  Bot, 
  MessageSquare,
  Lightbulb,
  ArrowRight
} from 'lucide-react';
import { apiService } from '../services/apiService';

export default function AiInsights({ onNavigate }) {
  const [insights, setInsights] = useState(apiService.getAiInsights());
  const [activeFilter, setActiveFilter] = useState('All');

  // AI Assistant Chat State
  const [query, setQuery] = useState('');
  const [chatLog, setChatLog] = useState([
    {
      sender: 'ai',
      text: 'Hello! I am your SmartServe AI Operations Assistant. Ask me anything about demand predictions, weather impact, or kitchen waste reduction recommendations.'
    }
  ]);
  const [isThinking, setIsThinking] = useState(false);

  const filters = ['All', 'Demand Forecast', 'Weather Alert', 'Waste Reduction', 'Kitchen Workflow'];

  const filteredInsights = insights.filter(i => activeFilter === 'All' || i.category === activeFilter);

  const handleSendQuery = (e) => {
    e.preventDefault();
    if (!query.trim()) return;

    const userText = query;
    setChatLog(prev => [...prev, { sender: 'user', text: userText }]);
    setQuery('');
    setIsThinking(true);

    setTimeout(() => {
      let aiResponse = "Based on machine learning models and 30-day historical POS trends: ";
      if (userText.toLowerCase().includes('biryani') || userText.toLowerCase().includes('tomorrow')) {
        aiResponse += "Demand for Veg Biryani & Chicken Dum Biryani is expected to increase tomorrow by +18% due to Friday evening peak. Increase prep buffer to 90 plates.";
      } else if (userText.toLowerCase().includes('rain') || userText.toLowerCase().includes('weather')) {
        aiResponse += "Rainy weather forecasted for tomorrow afternoon will reduce Cold Beverage orders by ~22% while boosting hot soup orders by +15%.";
      } else if (userText.toLowerCase().includes('waste') || userText.toLowerCase().includes('salad')) {
        aiResponse += "Fresh Garden Salad over-prep on Mondays accounts for 40% of weekly salad waste. We recommend shifting to 2-stage batch prep (10 bowls per batch).";
      } else {
        aiResponse += "Current operational efficiency is at 94.2%. Over-preparation waste has decreased by 32% this week, saving ₹14,850 in raw ingredient costs.";
      }

      setChatLog(prev => [...prev, { sender: 'ai', text: aiResponse }]);
      setIsThinking(false);
    }, 1000);
  };

  return (
    <div className="space-y-8 pb-12">
      {/* Header Banner */}
      <div className="bg-gradient-to-r from-[#081c15] via-[#112a12] to-[#1b4332] rounded-3xl p-6 md:p-8 text-white shadow-xl border border-emerald-800/30 flex flex-col md:flex-row items-start md:items-center justify-between gap-6">
        <div>
          <span className="text-xs font-bold uppercase tracking-wider text-amber-300 bg-amber-400/10 px-3 py-1 rounded-full border border-amber-400/30 inline-flex items-center gap-1.5 mb-2">
            <Sparkles className="w-3.5 h-3.5 text-[#d4af37]" /> DEDICATED AI INTELLIGENCE FEED
          </span>
          <h2 className="text-2xl md:text-3xl font-bold font-heading">
            SmartServe AI Insights
          </h2>
          <p className="text-xs md:text-sm text-gray-300 mt-1 max-w-xl">
            Proactive actionable recommendations automatically generated by machine learning pattern detection algorithms.
          </p>
        </div>

        <div className="bg-[#d4af37]/10 border border-[#d4af37]/30 p-4 rounded-2xl text-center shrink-0">
          <p className="text-xs text-amber-200 font-semibold">Active AI Engine</p>
          <p className="text-lg font-bold text-[#d4af37]">Real-time Pattern Scan</p>
        </div>
      </div>

      {/* Main Grid: Insights Cards & AI Assistant Chat */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Insights Column */}
        <div className="lg:col-span-2 space-y-5">
          {/* Category Filters */}
          <div className="flex items-center gap-2 overflow-x-auto pb-1">
            {filters.map(filter => (
              <button
                key={filter}
                onClick={() => setActiveFilter(filter)}
                className={`px-3.5 py-1.5 rounded-xl text-xs font-bold whitespace-nowrap transition-all cursor-pointer ${
                  activeFilter === filter
                    ? 'bg-[#1b4332] text-white shadow-sm'
                    : 'bg-white text-gray-700 hover:bg-gray-100 border border-gray-200'
                }`}
              >
                {filter}
              </button>
            ))}
          </div>

          {/* AI Cards List */}
          <div className="space-y-4">
            {filteredInsights.map(item => (
              <div 
                key={item.id} 
                className={`bg-white rounded-3xl p-6 shadow-xs border transition-all hover-card-rise relative overflow-hidden ${
                  item.type === 'warning'
                    ? 'border-orange-200 border-l-4 border-l-orange-500'
                    : item.type === 'critical'
                    ? 'border-red-200 border-l-4 border-l-red-500'
                    : item.type === 'opportunity'
                    ? 'border-emerald-200 border-l-4 border-l-[#1b4332]'
                    : 'border-amber-200 border-l-4 border-l-[#d4af37]'
                }`}
              >
                <div className="flex items-start justify-between gap-4">
                  <div className="space-y-1.5">
                    <div className="flex items-center gap-2">
                      <span className={`text-[10px] font-bold px-2.5 py-0.5 rounded-full uppercase tracking-wider ${
                        item.type === 'warning'
                          ? 'bg-orange-100 text-orange-800'
                          : item.type === 'critical'
                          ? 'bg-red-100 text-red-800'
                          : item.type === 'opportunity'
                          ? 'bg-emerald-100 text-emerald-800'
                          : 'bg-amber-100 text-amber-900'
                      }`}>
                        {item.category}
                      </span>
                      <span className="text-[10px] text-gray-400">• {item.time}</span>
                    </div>

                    <h3 className="text-lg font-bold font-heading text-gray-900">{item.title}</h3>
                    <p className="text-xs text-gray-700 leading-relaxed">{item.description}</p>
                  </div>

                  <span className="text-xs font-extrabold px-3 py-1 rounded-xl bg-gray-100 text-gray-800 border border-gray-200 shrink-0">
                    {item.metric}
                  </span>
                </div>

                <div className="mt-4 pt-3 border-t border-gray-100 flex items-center justify-between text-xs">
                  <span className="font-semibold text-gray-800 flex items-center gap-1.5">
                    <Lightbulb className="w-4 h-4 text-[#d4af37]" /> Recommended Action: <span className="text-[#1b4332]">{item.actionableText}</span>
                  </span>

                  <button
                    onClick={() => onNavigate('preparation')}
                    className="text-xs font-bold text-[#1b4332] hover:underline flex items-center gap-1 cursor-pointer"
                  >
                    <span>Execute</span> <ArrowRight className="w-3.5 h-3.5" />
                  </button>
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* Ask SmartServe AI Assistant Bot Panel */}
        <div className="bg-white rounded-3xl p-6 shadow-xs border border-gray-100 flex flex-col h-[520px] justify-between">
          <div>
            <div className="flex items-center gap-3 pb-4 border-b border-gray-100">
              <div className="w-10 h-10 rounded-2xl bg-[#081c15] text-white flex items-center justify-center border border-[#1b4332]">
                <Bot className="w-5 h-5 text-emerald-400" />
              </div>
              <div>
                <h3 className="text-sm font-bold font-heading text-gray-900">Ask SmartServe AI</h3>
                <span className="text-[10px] text-emerald-700 font-semibold flex items-center gap-1">
                  <span className="w-2 h-2 rounded-full bg-emerald-500 animate-ping" /> Online • Natural Language ML
                </span>
              </div>
            </div>

            {/* Chat Conversation Box */}
            <div className="mt-4 space-y-3 max-h-[320px] overflow-y-auto pr-1 text-xs">
              {chatLog.map((msg, index) => (
                <div 
                  key={index}
                  className={`p-3 rounded-2xl max-w-[90%] leading-relaxed ${
                    msg.sender === 'user'
                      ? 'bg-[#1b4332] text-white ml-auto rounded-br-xs'
                      : 'bg-gray-100 text-gray-800 rounded-bl-xs border border-gray-200'
                  }`}
                >
                  {msg.text}
                </div>
              ))}

              {isThinking && (
                <div className="p-3 rounded-2xl bg-gray-100 text-gray-500 text-xs italic animate-pulse">
                  SmartServe AI is analyzing POS demand trends...
                </div>
              )}
            </div>
          </div>

          {/* Chat Input */}
          <form onSubmit={handleSendQuery} className="pt-3 border-t border-gray-100 flex items-center gap-2">
            <input
              type="text"
              placeholder="e.g. Ask about Veg Biryani or Rain..."
              value={query}
              onChange={(e) => setQuery(e.target.value)}
              className="flex-1 bg-[#f4f6f0] border border-gray-300 rounded-xl px-3 py-2 text-xs font-semibold focus:outline-none focus:ring-2 focus:ring-[#1b4332]"
            />
            <button
              type="submit"
              className="p-2.5 rounded-xl bg-[#1b4332] hover:bg-[#2d6a4f] text-white transition-colors cursor-pointer"
            >
              <Send className="w-4 h-4" />
            </button>
          </form>
        </div>
      </div>
    </div>
  );
}
